run:
  concurrency: 16
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true
  go: '1.22.3'
linters-settings:
  depguard:
    rules:
      srcs:
        listMode: "Strict"
        allow:
        - $gostd
        - github.com/alecthomas/chroma/v2/quick
        - github.com/google/generative-ai-go
        - github.com/lrstanley/girc
        - github.com/sashabaranov/go-openai
        - github.com/BurntSushi/toml
        - github.com/jackc/pgx/v5
        - github.com/jackc/pgx/v5/pgxpool
        - github.com/jackc/pgx/v5/pgtype
        - github.com/yuin/gopher-lua
        - github.com/ailncode/gluaxmlpath
        - github.com/cjoudrey/gluahttp
        - github.com/kohkimakimoto/gluayaml
        - github.com/yuin/gluare
        - gitlab.com/megalithic-llc/gluasocket
        - github.com/layeh/gopher-json
        - github.com/mmcdole/gofeed
        - github.com/cenkalti/backoff/v5
        - golang.org/x/net/proxy
        - google.golang.org/genai
        - golang.org/x/net/html
        - github.com/ergochat/irc-go/ircmsg
