ircServer = "irc.libera.caht"
ircNick = "milla"
ircSaslUser = ""
ircSaslPass = ""
ollamaEndpoint = "http://127.0.0.1:11434/api/chat"
model = "ollama2-uncensored"
chromaStyle = "monokai"
chromaFormatter = "terminal16m"
provider = "ollama"
apikey = "xxx"
ollamaSystem = ""
clientCertPath = ""
serverPass = ""
bind = ""
temp = 0.5
requestTimeout = 10
millaReconnectDelay = 60
ircPort = 6669
keepAlive = 20
memoryLimit = 20
pingDelay = 20
pingTimeout = 600
topP = 0.9
topK = 0
enableSasl = false
skipTLSVerify = false
useTLS = true
disableSTSFallback = true
allowFlood = false
debug = false
out = false
admins = ["nick1", "nick2"]
ircChannels = ["##milla1", "##milla2"]
