FROM golang:1.24-alpine3.21 AS builder
WORKDIR /milla
COPY go.sum go.mod /milla/
COPY vendor /milla/vendor
COPY *.go /milla/
RUN CGO_ENABLED=0 go build

FROM alpine:3.21 AS cert
RUN apk add --no-cache ca-certificates

FROM scratch
COPY --from=cert /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /milla/milla "/milla"
ENTRYPOINT ["/milla"]
