version: "3.9"
services:
  milla:
    image: milla
    build:
      context: .
    deploy:
      resources:
        limits:
          memory: 64M
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      - millanet
    restart: unless-stopped
    command: ["--config", "/opt/milla/config.toml"]
    volumes:
      - ./config.toml:/opt/milla/config.toml
      - /etc/ssl/certs:/etc/ssl/certs:ro
    cap_drop:
      - ALL
    environment:
      - SERVER_DEPLOYMENT_TYPE=deployment
  # prettier:
  #   build:
  #     context: ./prettier
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 128M
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "100m"
  #   networks:
  #     - millanet
  #   restart: unless-stopped
  #   cap_drop:
  #     - ALL
  #   cap_add:
  #     - NET_BIND_SERVICE
  #   ports:
  #     - "127.0.0.1:9001:9001"
networks:
  millanet:
