FROM golang:1.24-alpine3.21 AS builder
WORKDIR /milla
COPY go.sum go.mod /milla/
COPY vendor /milla/vendor
COPY *.go /milla/
RUN CGO_ENABLED=0 go build

FROM golang:1.24-alpine3.21 AS debug
RUN CGO_ENABLED=0 go install -ldflags "-s -w -extldflags '-static'" github.com/go-delve/delve/cmd/dlv@latest

FROM alpine:3.21
COPY --from=debug /go/bin/dlv /usr/bin/dlv
COPY --from=builder /milla/milla "/usr/bin/milla"
ENTRYPOINT ["/usr/bin/dlv"]
