FROM golang:1.24-alpine3.21 AS builder
WORKDIR /milla
COPY go.sum go.mod /milla/
COPY vendor /milla/vendor
COPY *.go /milla/
RUN CGO_ENABLED=0 go build

FROM gcr.io/distroless/static-debian12
COPY --from=builder /milla/milla "/usr/bin/milla"
ENTRYPOINT ["milla"]
